# Generated by Django 4.2.1 on 2023-08-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ПВЗ')),
                ('rent_price', models.FloatField(default=0, verbose_name='Стоимость аренды(месяц)')),
                ('video_price', models.FloatField(default=0, verbose_name='Стоимость обслуживания камер(месяц)')),
                ('extra_serving_price', models.FloatField(default=0, verbose_name='Стоимость доп. обслуживания(месяц)')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=200, unique=True, verbose_name='ФИО сотрудника')),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='Дата трудоустройства')),
                ('salary', models.FloatField(default=0, verbose_name='Ставка за смену')),
                ('penalty', models.FloatField(default=0, verbose_name='Сумма штрафа')),
                ('pvz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='wildberries.pvz', verbose_name='ПВЗ сотрудника')),
            ],
        ),
    ]
