# Generated by Django 4.2.1 on 2023-08-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Дата начала периода')),
                ('to_date', models.DateField(verbose_name='Дата окончания периода')),
                ('charged_rate', models.FloatField(default=0, verbose_name='Начислено по тарифу')),
                ('charged_courier', models.FloatField(default=0, verbose_name='Доплата за выданное через курьера')),
                ('surcharge_motivation', models.FloatField(default=0, verbose_name='Доплата за мотивацию')),
                ('hold_motivation', models.FloatField(default=0, verbose_name='Удержание за мотивацию')),
                ('hold_rating', models.FloatField(default=0, verbose_name='Удержание за рейтинг')),
                ('surcharge_signage', models.FloatField(default=0, verbose_name='Доплата за вывеску')),
                ('surcharge_goods', models.FloatField(default=0, verbose_name='Доплата за товары')),
                ('hold_goods', models.FloatField(default=0, verbose_name='Удержание за товары')),
                ('hold_substitution', models.FloatField(default=0, verbose_name='Удержание за подмену товара')),
                ('hold_furniture', models.FloatField(default=0, verbose_name='Удержание за мебель')),
                ('hold_for_defects', models.FloatField(default=0, verbose_name='Удержание за брак')),
                ('subsidies', models.FloatField(default=0, verbose_name='Субсидии')),
                ('debt', models.FloatField(default=0, verbose_name='Долг')),
                ('penalty', models.FloatField(default=0, verbose_name='Штраф')),
                ('supplier_returns', models.FloatField(default=0, verbose_name='Возвраты поставщику')),
                ('extra_motivation', models.FloatField(default=0, verbose_name='Дополнительная мотивация')),
                ('zero_substitution_effect', models.FloatField(default=0, verbose_name='Нулевой эффект подмены')),
                ('return_incorrect_mark', models.FloatField(default=0, verbose_name='Возврат удержаний за некорректную отметку о браке')),
                ('extra_nds', models.FloatField(default=0, verbose_name='Доплата НДС')),
                ('package_compensation', models.FloatField(default=0, verbose_name='Компенсация за пакеты')),
                ('hold_non_returned', models.FloatField(default=0, verbose_name='Удержано за невозврат товара')),
                ('total', models.FloatField(default=0, verbose_name='Итого')),
                ('pvz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_payments', to='wildberries.pvz', verbose_name='ПВЗ')),
            ],
        ),
        migrations.CreateModel(
            name='PVZPaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Дата начала периода')),
                ('to_date', models.DateField(verbose_name='Дата окончания периода')),
                ('number_days', models.IntegerField(default=0, verbose_name='Отработано смен')),
                ('count_big_boxes', models.IntegerField(default=0, verbose_name='Количество коробок')),
                ('extra_boxes', models.IntegerField(default=0, verbose_name='Количество доп.коробок')),
                ('extra_payment', models.IntegerField(default=0, verbose_name='Бонус(руб.)')),
                ('add_penalty', models.IntegerField(default=0, verbose_name='Сумма начисленного штраф')),
                ('surcharge_penalty', models.IntegerField(default=0, verbose_name='Сумма удержанного штрафа')),
                ('total', models.IntegerField(default=0, verbose_name='Итого к выплате')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wildberries.employee', verbose_name='Сотрудник')),
                ('pvz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvz_payments', to='wildberries.pvz', verbose_name='ПВЗ')),
            ],
        ),
    ]
