# Generated by Django 4.2.1 on 2023-08-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0002_wbpayment_pvzpaiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbpayment',
            name='total_charge',
            field=models.FloatField(default=0, verbose_name='Всего начислено'),
        ),
        migrations.AddField(
            model_name='wbpayment',
            name='total_hold',
            field=models.FloatField(default=0, verbose_name='Всего удержано'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='penalty',
            field=models.FloatField(default=0, verbose_name='Сумма к удержанию'),
        ),
        migrations.AlterField(
            model_name='wbpayment',
            name='total',
            field=models.FloatField(default=0, verbose_name='Доход'),
        ),
    ]
