# Generated by Django 4.1.7 on 2023-08-14 04:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0003_wbpayment_total_charge_wbpayment_total_hold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvzpaiment',
            old_name='count_big_boxes',
            new_name='boxes_count',
        ),
        migrations.RemoveField(
            model_name='pvzpaiment',
            name='extra_boxes',
        ),
        migrations.RemoveField(
            model_name='pvzpaiment',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='pvzpaiment',
            name='to_date',
        ),
        migrations.AddField(
            model_name='pvzpaiment',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата выплаты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='penalty',
            field=models.FloatField(default=0, verbose_name='Накопленный штраф'),
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='add_penalty',
            field=models.IntegerField(default=0, verbose_name='Штраф к начислеению'),
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='pvz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvz_payments', to='wildberries.pvz', verbose_name='Пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='surcharge_penalty',
            field=models.IntegerField(default=0, verbose_name='Штраф к удержанию'),
        ),
    ]
