# Generated by Django 4.1.7 on 2023-08-21 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0004_rename_count_big_boxes_pvzpaiment_boxes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='add_penalty',
            field=models.IntegerField(default=0, verbose_name='Штраф к начислению'),
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='boxes_count',
            field=models.IntegerField(default=0, verbose_name='Коробки'),
        ),
        migrations.AlterField(
            model_name='pvzpaiment',
            name='number_days',
            field=models.IntegerField(default=0, verbose_name='Cмены'),
        ),
        migrations.CreateModel(
            name='PVZOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='wildberries.category', verbose_name='Категория')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='wildberries.pvz', verbose_name='ПВЗ')),
            ],
        ),
    ]
