# Generated by Django 4.1.7 on 2023-08-21 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0005_category_alter_pvzpaiment_add_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvzpaiment',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pvzoutcomes',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pvzoutcomes',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pvzoutcomes',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
