# Generated by Django 4.1.7 on 2023-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0006_pvzpaiment_is_closed_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
