# Generated by Django 4.1.7 on 2023-09-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wildberries', '0009_wallettransaction_source_alter_wallet_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='source',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contenttypes.contenttype', verbose_name='Основание'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
