# Generated by Django 4.2.1 on 2023-08-08 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_income_date_of_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 2, 44, 1, 778056, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 2, 44, 1, 780215, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
