# Generated by Django 4.1.7 on 2023-03-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Category title')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=3, unique=True, verbose_name='Short view')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Source title')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency')),
            ],
        ),
        migrations.CreateModel(
            name='RegularOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Outcome')),
                ('period', models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('y', 'Year')], max_length=10, verbose_name='Period of outcome')),
                ('sum', models.FloatField(default=0, verbose_name='Sum of outcome')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Date of beginning')),
                ('end_date', models.DateField(null=True, verbose_name='Date of ending')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='accounting.category')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_operation', models.DateTimeField(auto_now_add=True, verbose_name='Date of operation')),
                ('sum', models.FloatField(default=0, verbose_name='Summ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_category', to='accounting.category')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_currency', to='accounting.currency')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_source', to='accounting.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
