# Generated by Django 4.1.7 on 2023-03-22 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 2, 38, 52, 92557, tzinfo=datetime.timezone.utc), verbose_name='Date of operation'),
        ),
        migrations.AlterField(
            model_name='income',
            name='sum',
            field=models.FloatField(default=0, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of ending'),
        ),
    ]
