# Generated by Django 4.1.7 on 2023-03-22 07:15

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_alter_income_date_of_operation_alter_income_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=3, unique=True, verbose_name='Короткий код'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_category', to='accounting.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_currency', to='accounting.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 7, 15, 18, 858620, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_by_source', to='accounting.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='income',
            name='sum',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='accounting.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='period',
            field=models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('y', 'Year')], max_length=10, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='sum',
            field=models.FloatField(default=0, verbose_name='Сумма расхода'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='source',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency', verbose_name='Валюта'),
        ),
    ]
