# Generated by Django 4.1.7 on 2023-03-22 10:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_income_status_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default='', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 10, 27, 32, 985231, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
