# Generated by Django 4.1.7 on 2023-03-31 02:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_regularoutcome_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 2, 38, 42, 788969, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 2, 38, 42, 792409, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
