# Generated by Django 4.1.7 on 2023-03-31 11:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_income_date_of_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularoutcome',
            name='sum_in_default_currency',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма в пересчета на валюту учета'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 11, 39, 37, 285706, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 11, 39, 37, 296112, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
