# Generated by Django 4.2.1 on 2023-08-08 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_regularoutcome_sum_in_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 2, 51, 50, 255065, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 2, 51, 50, 257149, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
