# Generated by Django 4.2.1 on 2023-08-08 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_income_date_of_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_of_operation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 5, 31, 45, 58675, tzinfo=datetime.timezone.utc), verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='regularoutcome',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 5, 31, 45, 60718, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
